// <auto-generated />
using System;
using Fundo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fundo.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250807020340_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fundo.Domain.Entities.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LoandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Histories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2024, 8, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan created: Amount $1,500.00",
                            LoandId = new Guid("1a58dcd6-4562-4e1e-9aa9-02129a2f1c01")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2024, 8, 3, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Payment of $800.00 received",
                            LoandId = new Guid("1a58dcd6-4562-4e1e-9aa9-02129a2f1c01")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2024, 8, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Payment of $200.00 received",
                            LoandId = new Guid("1a58dcd6-4562-4e1e-9aa9-02129a2f1c01")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2024, 8, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan created: Amount $1,000.00",
                            LoandId = new Guid("2b3c934a-78d2-4b56-a5d4-55a83954ae02")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2024, 8, 5, 13, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Loan fully paid",
                            LoandId = new Guid("2b3c934a-78d2-4b56-a5d4-55a83954ae02")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2024, 8, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan created: Amount $5,000.00",
                            LoandId = new Guid("3c1a2d9f-d8f1-4f45-8b90-49a2780b1f03")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2024, 8, 2, 15, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Interest charged: $50.00",
                            LoandId = new Guid("3c1a2d9f-d8f1-4f45-8b90-49a2780b1f03")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2024, 8, 4, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Payment of $1,000.00 received",
                            LoandId = new Guid("3c1a2d9f-d8f1-4f45-8b90-49a2780b1f03")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2024, 8, 6, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Payment of $1,500.00 received",
                            LoandId = new Guid("3c1a2d9f-d8f1-4f45-8b90-49a2780b1f03")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(2024, 8, 8, 18, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Late fee charged: $10.00",
                            LoandId = new Guid("3c1a2d9f-d8f1-4f45-8b90-49a2780b1f03")
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2024, 8, 3, 13, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan created: Amount $7,500.00",
                            LoandId = new Guid("4db4e8ae-d0ff-49fd-ae13-bb3e9f4b3a04")
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2024, 8, 7, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Payment of $5,000.00 received",
                            LoandId = new Guid("4db4e8ae-d0ff-49fd-ae13-bb3e9f4b3a04")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2024, 8, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan created: Amount $2,000.00",
                            LoandId = new Guid("5c334e60-81a2-42a0-89e2-0f80c4b1e405")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2024, 8, 3, 13, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Payment of $1,000.00 received",
                            LoandId = new Guid("5c334e60-81a2-42a0-89e2-0f80c4b1e405")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2024, 8, 4, 15, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan fully paid",
                            LoandId = new Guid("5c334e60-81a2-42a0-89e2-0f80c4b1e405")
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2024, 8, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan created: Amount $12,000.00",
                            LoandId = new Guid("6a223421-38a9-43ff-b7b2-dab9b5e8e206")
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2024, 8, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Interest charged: $100.00",
                            LoandId = new Guid("6a223421-38a9-43ff-b7b2-dab9b5e8e206")
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2024, 8, 4, 17, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Payment of $4,000.00 received",
                            LoandId = new Guid("6a223421-38a9-43ff-b7b2-dab9b5e8e206")
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2024, 8, 6, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Partial payment received",
                            LoandId = new Guid("6a223421-38a9-43ff-b7b2-dab9b5e8e206")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2024, 8, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan created: Amount $3,000.00",
                            LoandId = new Guid("7e21f316-9475-4a3e-9c6d-61c5f1a3b207")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2024, 8, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Payment of $1,500.00 received",
                            LoandId = new Guid("7e21f316-9475-4a3e-9c6d-61c5f1a3b207")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2024, 8, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan created: Amount $900.00",
                            LoandId = new Guid("8f42e9a1-3cdd-470b-8779-319ae346f508")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2024, 8, 4, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan fully paid",
                            LoandId = new Guid("8f42e9a1-3cdd-470b-8779-319ae346f508")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2024, 8, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan created: Amount $6,500.00",
                            LoandId = new Guid("9c01fd52-780c-4e84-9ef1-5a3e3c0a5909")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2024, 8, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Interest charged: $70.00",
                            LoandId = new Guid("9c01fd52-780c-4e84-9ef1-5a3e3c0a5909")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2024, 8, 4, 15, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Payment of $2,000.00 received",
                            LoandId = new Guid("9c01fd52-780c-4e84-9ef1-5a3e3c0a5909")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2024, 8, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Payment of $1,500.00 received",
                            LoandId = new Guid("9c01fd52-780c-4e84-9ef1-5a3e3c0a5909")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(2024, 8, 9, 18, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Partial payment received",
                            LoandId = new Guid("9c01fd52-780c-4e84-9ef1-5a3e3c0a5909")
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000001"),
                            Created = new DateTime(2024, 8, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan created: Amount $4,000.00",
                            LoandId = new Guid("10ffbc7e-212f-4fc7-a3ee-9437e66e7e10")
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000002"),
                            Created = new DateTime(2024, 8, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Payment of $2,000.00 received",
                            LoandId = new Guid("10ffbc7e-212f-4fc7-a3ee-9437e66e7e10")
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000003"),
                            Created = new DateTime(2024, 8, 7, 17, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan fully paid",
                            LoandId = new Guid("10ffbc7e-212f-4fc7-a3ee-9437e66e7e10")
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2024, 8, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan created: Amount $10,000.00",
                            LoandId = new Guid("11aaf61e-4de7-4607-b9fd-dbc81d15cb11")
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2024, 8, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Interest charged: $120.00",
                            LoandId = new Guid("11aaf61e-4de7-4607-b9fd-dbc81d15cb11")
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2024, 8, 4, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Payment of $2,500.00 received",
                            LoandId = new Guid("11aaf61e-4de7-4607-b9fd-dbc81d15cb11")
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2024, 8, 5, 13, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Late fee charged: $40.00",
                            LoandId = new Guid("11aaf61e-4de7-4607-b9fd-dbc81d15cb11")
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(2024, 8, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Partial payment received",
                            LoandId = new Guid("11aaf61e-4de7-4607-b9fd-dbc81d15cb11")
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(2024, 8, 9, 15, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan extension requested",
                            LoandId = new Guid("11aaf61e-4de7-4607-b9fd-dbc81d15cb11")
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2024, 8, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loan created: Amount $2,500.00",
                            LoandId = new Guid("12bbc84e-5ad8-4c6a-b637-e2cc087c5d12")
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2024, 8, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Payment of $2,000.00 received",
                            LoandId = new Guid("12bbc84e-5ad8-4c6a-b637-e2cc087c5d12")
                        });
                });

            modelBuilder.Entity("Fundo.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a58dcd6-4562-4e1e-9aa9-02129a2f1c01"),
                            Amount = 1500m,
                            ApplicantName = "Maria Silva",
                            CurrentBalance = 500m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("2b3c934a-78d2-4b56-a5d4-55a83954ae02"),
                            Amount = 1000m,
                            ApplicantName = "João Souza",
                            CurrentBalance = 0m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("3c1a2d9f-d8f1-4f45-8b90-49a2780b1f03"),
                            Amount = 5000m,
                            ApplicantName = "Alice Johnson",
                            CurrentBalance = 5000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4db4e8ae-d0ff-49fd-ae13-bb3e9f4b3a04"),
                            Amount = 7500m,
                            ApplicantName = "Michael Smith",
                            CurrentBalance = 2500m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("5c334e60-81a2-42a0-89e2-0f80c4b1e405"),
                            Amount = 2000m,
                            ApplicantName = "Laura Martinez",
                            CurrentBalance = 0m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("6a223421-38a9-43ff-b7b2-dab9b5e8e206"),
                            Amount = 12000m,
                            ApplicantName = "Daniel Kim",
                            CurrentBalance = 12000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("7e21f316-9475-4a3e-9c6d-61c5f1a3b207"),
                            Amount = 3000m,
                            ApplicantName = "Emma Brown",
                            CurrentBalance = 1500m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8f42e9a1-3cdd-470b-8779-319ae346f508"),
                            Amount = 900m,
                            ApplicantName = "Lucas Williams",
                            CurrentBalance = 0m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("9c01fd52-780c-4e84-9ef1-5a3e3c0a5909"),
                            Amount = 6500m,
                            ApplicantName = "Olivia Davis",
                            CurrentBalance = 3000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("10ffbc7e-212f-4fc7-a3ee-9437e66e7e10"),
                            Amount = 4000m,
                            ApplicantName = "Ethan Wilson",
                            CurrentBalance = 0m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("11aaf61e-4de7-4607-b9fd-dbc81d15cb11"),
                            Amount = 10000m,
                            ApplicantName = "Sophia Moore",
                            CurrentBalance = 10000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("12bbc84e-5ad8-4c6a-b637-e2cc087c5d12"),
                            Amount = 2500m,
                            ApplicantName = "Gabriel Taylor",
                            CurrentBalance = 500m,
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
