// <auto-generated />
using System;
using Fundo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fundo.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250807014901_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fundo.Domain.Entities.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LoandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Histories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57a139a7-5b4d-43a8-8440-0c3b992576c8"),
                            Created = new DateTime(2025, 7, 28, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(1440),
                            Description = "Loan created: Amount $1,500.00",
                            LoandId = new Guid("1a58dcd6-4562-4e1e-9aa9-02129a2f1c01")
                        },
                        new
                        {
                            Id = new Guid("5d36c62a-7f07-48d2-b180-c726b890aece"),
                            Created = new DateTime(2025, 8, 2, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2650),
                            Description = "Payment of $1,000.00 received",
                            LoandId = new Guid("1a58dcd6-4562-4e1e-9aa9-02129a2f1c01")
                        },
                        new
                        {
                            Id = new Guid("1b52e0e5-6700-4fac-8eea-5c5f7d120f7f"),
                            Created = new DateTime(2025, 7, 26, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2670),
                            Description = "Loan created: Amount $1,000.00",
                            LoandId = new Guid("2b3c934a-78d2-4b56-a5d4-55a83954ae02")
                        },
                        new
                        {
                            Id = new Guid("276d8e01-6745-4585-bdfa-6c0c05db9724"),
                            Created = new DateTime(2025, 8, 4, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2670),
                            Description = "Loan fully paid",
                            LoandId = new Guid("2b3c934a-78d2-4b56-a5d4-55a83954ae02")
                        },
                        new
                        {
                            Id = new Guid("3809de77-1778-4a1f-9a49-970e41e7b41d"),
                            Created = new DateTime(2025, 7, 18, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Loan created: Amount $5,000.00",
                            LoandId = new Guid("3c1a2d9f-d8f1-4f45-8b90-49a2780b1f03")
                        },
                        new
                        {
                            Id = new Guid("a5dd33d8-16d4-4278-b6d9-7d7c57058f84"),
                            Created = new DateTime(2025, 7, 28, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Interest charged: $50.00",
                            LoandId = new Guid("3c1a2d9f-d8f1-4f45-8b90-49a2780b1f03")
                        },
                        new
                        {
                            Id = new Guid("3d756b5e-2017-4aa5-8363-af0ad151e985"),
                            Created = new DateTime(2025, 7, 23, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Loan created: Amount $7,500.00",
                            LoandId = new Guid("4db4e8ae-d0ff-49fd-ae13-bb3e9f4b3a04")
                        },
                        new
                        {
                            Id = new Guid("5717a56a-2ab9-4c32-8736-e024830b051c"),
                            Created = new DateTime(2025, 8, 5, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Payment of $5,000.00 received",
                            LoandId = new Guid("4db4e8ae-d0ff-49fd-ae13-bb3e9f4b3a04")
                        },
                        new
                        {
                            Id = new Guid("3132c1c3-8208-4910-8088-a1abc8754c8a"),
                            Created = new DateTime(2025, 7, 25, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Loan created: Amount $2,000.00",
                            LoandId = new Guid("5c334e60-81a2-42a0-89e2-0f80c4b1e405")
                        },
                        new
                        {
                            Id = new Guid("081d1de5-eb89-4d5f-bffc-ab502021f4c6"),
                            Created = new DateTime(2025, 8, 6, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Loan fully paid",
                            LoandId = new Guid("5c334e60-81a2-42a0-89e2-0f80c4b1e405")
                        },
                        new
                        {
                            Id = new Guid("df249249-f1ff-4aac-a3f4-0b7aec659ac5"),
                            Created = new DateTime(2025, 7, 8, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2700),
                            Description = "Loan created: Amount $12,000.00",
                            LoandId = new Guid("6a223421-38a9-43ff-b7b2-dab9b5e8e206")
                        },
                        new
                        {
                            Id = new Guid("4fce586f-1024-4fbe-a2ef-151d9302ec2d"),
                            Created = new DateTime(2025, 7, 23, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2700),
                            Description = "Interest charged: $100.00",
                            LoandId = new Guid("6a223421-38a9-43ff-b7b2-dab9b5e8e206")
                        },
                        new
                        {
                            Id = new Guid("35c66de0-e58f-4274-8603-b470c50e821b"),
                            Created = new DateTime(2025, 8, 1, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Loan created: Amount $3,000.00",
                            LoandId = new Guid("7e21f316-9475-4a3e-9c6d-61c5f1a3b207")
                        },
                        new
                        {
                            Id = new Guid("33ca418f-a02f-49e1-8bfe-aebcec982ee6"),
                            Created = new DateTime(2025, 8, 5, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Payment of $1,500.00 received",
                            LoandId = new Guid("7e21f316-9475-4a3e-9c6d-61c5f1a3b207")
                        },
                        new
                        {
                            Id = new Guid("b407aca7-d81d-4d02-b184-2a03fd60998c"),
                            Created = new DateTime(2025, 7, 30, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Loan created: Amount $900.00",
                            LoandId = new Guid("8f42e9a1-3cdd-470b-8779-319ae346f508")
                        },
                        new
                        {
                            Id = new Guid("5c8a2094-98c2-46c8-9dc4-a888ff095310"),
                            Created = new DateTime(2025, 8, 5, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Loan fully paid",
                            LoandId = new Guid("8f42e9a1-3cdd-470b-8779-319ae346f508")
                        },
                        new
                        {
                            Id = new Guid("9ea32480-1753-4b01-baf4-9e4748ce5022"),
                            Created = new DateTime(2025, 7, 24, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Loan created: Amount $6,500.00",
                            LoandId = new Guid("9c01fd52-780c-4e84-9ef1-5a3e3c0a5909")
                        },
                        new
                        {
                            Id = new Guid("60488e8a-69e4-4b9e-8dd3-9d67d29811b5"),
                            Created = new DateTime(2025, 8, 2, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Payment of $3,500.00 received",
                            LoandId = new Guid("9c01fd52-780c-4e84-9ef1-5a3e3c0a5909")
                        },
                        new
                        {
                            Id = new Guid("feb2efe6-2c0c-48f1-af5b-f901c443c5b8"),
                            Created = new DateTime(2025, 7, 28, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Loan created: Amount $4,000.00",
                            LoandId = new Guid("10ffbc7e-212f-4fc7-a3ee-9437e66e7e10")
                        },
                        new
                        {
                            Id = new Guid("d2566068-2d4c-4e28-a683-c280a9f011f9"),
                            Created = new DateTime(2025, 8, 6, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Loan fully paid",
                            LoandId = new Guid("10ffbc7e-212f-4fc7-a3ee-9437e66e7e10")
                        },
                        new
                        {
                            Id = new Guid("b80218af-fb48-4823-bd1f-14a64039f80a"),
                            Created = new DateTime(2025, 7, 17, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2740),
                            Description = "Loan created: Amount $10,000.00",
                            LoandId = new Guid("11aaf61e-4de7-4607-b9fd-dbc81d15cb11")
                        },
                        new
                        {
                            Id = new Guid("d5bd9efc-d845-4525-9f79-930038121ff6"),
                            Created = new DateTime(2025, 7, 31, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2740),
                            Description = "Interest charged: $120.00",
                            LoandId = new Guid("11aaf61e-4de7-4607-b9fd-dbc81d15cb11")
                        },
                        new
                        {
                            Id = new Guid("452457a2-f3c6-4592-9e4a-ece7386e8c31"),
                            Created = new DateTime(2025, 7, 27, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2740),
                            Description = "Loan created: Amount $2,500.00",
                            LoandId = new Guid("12bbc84e-5ad8-4c6a-b637-e2cc087c5d12")
                        },
                        new
                        {
                            Id = new Guid("ed813d06-d247-431a-9a4f-50dbbe8acd6a"),
                            Created = new DateTime(2025, 8, 4, 1, 49, 0, 815, DateTimeKind.Utc).AddTicks(2750),
                            Description = "Payment of $2,000.00 received",
                            LoandId = new Guid("12bbc84e-5ad8-4c6a-b637-e2cc087c5d12")
                        });
                });

            modelBuilder.Entity("Fundo.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a58dcd6-4562-4e1e-9aa9-02129a2f1c01"),
                            Amount = 1500m,
                            ApplicantName = "Maria Silva",
                            CurrentBalance = 500m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("2b3c934a-78d2-4b56-a5d4-55a83954ae02"),
                            Amount = 1000m,
                            ApplicantName = "João Souza",
                            CurrentBalance = 0m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("3c1a2d9f-d8f1-4f45-8b90-49a2780b1f03"),
                            Amount = 5000m,
                            ApplicantName = "Alice Johnson",
                            CurrentBalance = 5000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4db4e8ae-d0ff-49fd-ae13-bb3e9f4b3a04"),
                            Amount = 7500m,
                            ApplicantName = "Michael Smith",
                            CurrentBalance = 2500m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("5c334e60-81a2-42a0-89e2-0f80c4b1e405"),
                            Amount = 2000m,
                            ApplicantName = "Laura Martinez",
                            CurrentBalance = 0m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("6a223421-38a9-43ff-b7b2-dab9b5e8e206"),
                            Amount = 12000m,
                            ApplicantName = "Daniel Kim",
                            CurrentBalance = 12000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("7e21f316-9475-4a3e-9c6d-61c5f1a3b207"),
                            Amount = 3000m,
                            ApplicantName = "Emma Brown",
                            CurrentBalance = 1500m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8f42e9a1-3cdd-470b-8779-319ae346f508"),
                            Amount = 900m,
                            ApplicantName = "Lucas Williams",
                            CurrentBalance = 0m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("9c01fd52-780c-4e84-9ef1-5a3e3c0a5909"),
                            Amount = 6500m,
                            ApplicantName = "Olivia Davis",
                            CurrentBalance = 3000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("10ffbc7e-212f-4fc7-a3ee-9437e66e7e10"),
                            Amount = 4000m,
                            ApplicantName = "Ethan Wilson",
                            CurrentBalance = 0m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("11aaf61e-4de7-4607-b9fd-dbc81d15cb11"),
                            Amount = 10000m,
                            ApplicantName = "Sophia Moore",
                            CurrentBalance = 10000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("12bbc84e-5ad8-4c6a-b637-e2cc087c5d12"),
                            Amount = 2500m,
                            ApplicantName = "Gabriel Taylor",
                            CurrentBalance = 500m,
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
