// <auto-generated />
using System;
using Fundo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fundo.Infrastructure.Migrations.HistoryDb
{
    [DbContext(typeof(HistoryDbContext))]
    [Migration("20250806204634_AddHistory")]
    partial class AddHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fundo.Domain.Entities.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LoandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("History");
                });

            modelBuilder.Entity("Fundo.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Loan");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a58dcd6-4562-4e1e-9aa9-02129a2f1c01"),
                            Amount = 1500m,
                            ApplicantName = "Maria Silva",
                            CurrentBalance = 500m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("2b3c934a-78d2-4b56-a5d4-55a83954ae02"),
                            Amount = 1000m,
                            ApplicantName = "João Souza",
                            CurrentBalance = 0m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("3c1a2d9f-d8f1-4f45-8b90-49a2780b1f03"),
                            Amount = 5000m,
                            ApplicantName = "Alice Johnson",
                            CurrentBalance = 5000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4db4e8ae-d0ff-49fd-ae13-bb3e9f4b3a04"),
                            Amount = 7500m,
                            ApplicantName = "Michael Smith",
                            CurrentBalance = 2500m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("5c334e60-81a2-42a0-89e2-0f80c4b1e405"),
                            Amount = 2000m,
                            ApplicantName = "Laura Martinez",
                            CurrentBalance = 0m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("6a223421-38a9-43ff-b7b2-dab9b5e8e206"),
                            Amount = 12000m,
                            ApplicantName = "Daniel Kim",
                            CurrentBalance = 12000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("7e21f316-9475-4a3e-9c6d-61c5f1a3b207"),
                            Amount = 3000m,
                            ApplicantName = "Emma Brown",
                            CurrentBalance = 1500m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8f42e9a1-3cdd-470b-8779-319ae346f508"),
                            Amount = 900m,
                            ApplicantName = "Lucas Williams",
                            CurrentBalance = 0m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("9c01fd52-780c-4e84-9ef1-5a3e3c0a5909"),
                            Amount = 6500m,
                            ApplicantName = "Olivia Davis",
                            CurrentBalance = 3000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("10ffbc7e-212f-4fc7-a3ee-9437e66e7e10"),
                            Amount = 4000m,
                            ApplicantName = "Ethan Wilson",
                            CurrentBalance = 0m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("11aaf61e-4de7-4607-b9fd-dbc81d15cb11"),
                            Amount = 10000m,
                            ApplicantName = "Sophia Moore",
                            CurrentBalance = 10000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("12bbc84e-5ad8-4c6a-b637-e2cc087c5d12"),
                            Amount = 2500m,
                            ApplicantName = "Gabriel Taylor",
                            CurrentBalance = 500m,
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
